# Generated by Django 2.2.10 on 2021-09-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_role',
            fields=[
                ('id_position', models.AutoField(primary_key=True, serialize=False)),
                ('name_position', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Employee_rol',
                'verbose_name_plural': 'Employee_rols',
                'db_table': 'employee_rol',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('identification_number', models.CharField(max_length=10, unique=True, verbose_name='cedula')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('date_of_birth', models.DateField()),
                ('assigned_boss', models.IntegerField()),
                ('fk_employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee_role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
            },
        ),
    ]
